# Generated by Django 4.0.6 on 2022-09-06 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_receives', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_delivers', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-modification_date'],
            },
        ),
    ]
