# Generated by Django 4.0.6 on 2022-09-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/assets/images/hawksbill.png', null=True, upload_to='profile/', verbose_name='Profile image'),
        ),
    ]
