# Generated by Django 4.0.6 on 2022-09-06 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationTokenDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('detail', models.CharField(max_length=50, unique=True, verbose_name='Detail')),
                ('acronym', models.CharField(max_length=3, unique=True, verbose_name='Acronym')),
            ],
            options={
                'verbose_name': 'Confirmation token detail',
                'verbose_name_plural': 'Confirmation token details',
                'ordering': ['detail'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('acronym', models.CharField(max_length=3, unique=True, verbose_name='Acronym')),
            ],
            options={
                'verbose_name': 'Document type',
                'verbose_name_plural': 'Document types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmationToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hawksbillapi.confirmationtokendetail', verbose_name='Detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Confirmation token',
                'verbose_name_plural': 'Confirmation tokens',
                'ordering': ['user', 'detail'],
            },
        ),
    ]
