# Generated by Django 4.0.6 on 2022-09-06 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('access_url', models.URLField(verbose_name='Access URL')),
                ('user', models.CharField(max_length=50, verbose_name='User')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicensingTables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Serial number')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Activation date')),
                ('days', models.PositiveIntegerField(verbose_name='Number of days')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Is the license active?')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Licensing table',
                'verbose_name_plural': 'Licensing tables',
                'ordering': ['-modification_date'],
            },
        ),
    ]
