# Generated by Django 4.0.6 on 2022-09-06 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Request type',
                'verbose_name_plural': 'Request types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_closed', models.BooleanField(default=False, verbose_name='¿Has the request been closed?')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='¿Who delivers?')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician', to=settings.AUTH_USER_MODEL, verbose_name='¿Who receives?')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientrequests.requesttype', verbose_name='Request type')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['applicant'],
            },
        ),
    ]
