# Generated by Django 4.0.6 on 2022-09-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientrequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (A.I)')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, verbose_name='Status for logical elimination')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(default='assets/images/hawksbill.png', upload_to='client/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientrequests.client', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
