# Generated by Django 4.0.6 on 2022-09-08 21:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientrequests', '0002_client_clientrequest_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
